### ISSUE TITLE
GKE: remove helm dependecy by generating helm template

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#103]
What we have in [provisioner](https://github.com/scylladb/scylla-operator/tree/master/examples/gke/provisioner) should be updated and moved to top level directory. 
We should use a generated file for simplicity.

See:

https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/helm

**Comment by mmatczuk** [comment]
As a side note it's worth to notice that there is bunch of ways a device can be cleaned 

```
root@3cbc09a09042:/scripts# ls                 
blkdiscard.sh  common.sh  dd_zero.sh  fsclean.sh  quick_reset.sh  shred.sh
```

Shred seems to be a good choice if using LVM 

https://docs.mirantis.com/mcp/q4-18/mcp-operations-guide/tshooting/tshoot-mcp-openstack/shred-ionice.html

With scylla_raid_setup this this may not be the case if there is one disk (EKS).

**Comment by dahankzter** [comment]
Why do we need to eliminate Helm? It's the canonical tool to install and deploy things afaik.
Generating templates can be valuable anyway is it enables us to do something better but just to remove helm seems to not make sense. What I heard is that many would like a helm chart to install and configure scylla rather than the kustomize way we use today.

**Comment by dahankzter** [comment]
We also use Helm for Grafana and Prometheus.

**Comment by mmatczuk** [comment]
The only place I see helm in gke.sh is here. My point is that provisioner is generic and could be moved up.

**Comment by dahankzter** [comment]
Ok in the script itself it's only used to provision disks. :)
