### ISSUE TITLE
Helm Charts for Operator, Scylla Manager & Scylla DB

### ISSUE THREAD

**Issue by argunasekhar** [scylladb/scylla-operator#131]
Please provide, Helm Charts for Scylla Operator, Scylla Manager & Scylla DB
also enable ipv6 support for operator based deployments in kubernetes environmnet.

**Comment by dahankzter** [comment]
There is an issue for a Helm chart for the operator here #42 and the operator handles Scylla DB so that's not needed. Perhaps we can also provide a special Helm chart for Manager or let the Operator deploy it as well.
IP v4/v6 deserves a separate issue in itself since it's not really related to Helm charts.

**Comment by mmatczuk** [comment]
Work moved to #42
