### ISSUE TITLE
Consider using less common kind

### ISSUE THREAD

**Issue by kvaps** [scylladb/scylla-operator#144]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

I would suggest to replace wide meaning kind name  `kind: Cluster` to something less common.

Most of the operators using own kinds, eg:
- Elasticsearch operator uses `kind: Elasticsearch`
- Redis operator uses `kind: RedisCluster`
- PostgreSQL operator uses `kind: postgresql`
- Cassandra operator uses `kind: CassandraDatacenter`

Scylla-operator should use something simmilar.

**What is use case behind this feature:**

Using so wide meaning kinds is not common in Kubernetes.

**Additional Information:**

**Comment by mmatczuk** [comment]
Thanks for reporting.

**Comment by espindola** [comment]
I agree with the suggestion. While it is possible to use the group to disambiguate, it is nicer to say

```
$ kubectl get ScyllaCluster
```

than

```
$ kubectl get Cluster.scylla.scylladb.com
```

Changing just this seems "simple": Edit config/operator/crd/bases/scylla.scylladb.com_clusters.yaml to change kind, listKind, plural and singular and fix other places in the code that expect the old names.

What is not clear is how to do this without breaking compatibility.  According to  https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning, we can change the version, but changing the name will create a new CRD.

We would still have to handle the old name for some time, no? In order to make it possible to transition I think we also have to handle having both a Cluster and a SclyllaCluster that refer to the same resources, so that we don't duplicate the installation during the transition.

@mmatczuk check?

**Comment by mmatczuk** [comment]
This change is simple and is targeting 1.0 release. I think we can leave 0.x with the old spec and release 1.0 with a new spec. This needs to be documented in the release notes.

**Comment by espindola** [comment]
> This change is simple and is targeting 1.0 release. I think we can leave 0.x with the old spec and release 1.0 with a new spec. This needs to be documented in the release notes.

That is good news. I am giving this a try.
