### ISSUE TITLE
Changing default zone and region in "Deploying Scylla on EKS" is not supported

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1462]
[Deploying Scylla on EKS](https://operator.docs.scylladb.com/stable/eks.html) page of our documentation has a script prepared which allows for changing zone and region, yet the ScyllaCluster yaml has these values hardcoded not only for names, but also for node affinities. Therefore configuring the zones will actually cause the ScyllaCluster to never be scheduled.

**Comment by tnozicka** [comment]
I am not excited about having those scripts around as the matrix is too large to test and vouch for them. One setup that's tested and works would be better then options that don't. 
(Even as one of the main developers I don't use them at all because they are opinionated, I choose gitops or GKE UI instead.)

**Comment by rzetelskik** [comment]
I actually use those scripts, but they usually require a lot of tweaks anyway. I agree that they should go; there's too many things that can quickly go out of date right now and historically we haven't paid any attention to those.
