### ISSUE TITLE
docs: Issue in page Deploying Scylla on a Kubernetes Cluster

### ISSUE THREAD

**Issue by ivenn-scylladb** [scylladb/scylla-operator#1622]
I would like to report an issue in page https://operator.docs.scylladb.com/v1.11/generic

### Problem
This does not appear to be up to date with the latest repo.  Deployment of cluster.yaml fails because it does not exist in the cloned repo

###  Suggest a fix

**Comment by rzetelskik** [comment]
@ivenn-scylladb since you're looking at the last stable version of the documentation - v1.11, you also need to clone a corresponding version of the repository. The manifest is still there: https://github.com/scylladb/scylla-operator/blob/v1.11/examples/generic/cluster.yaml. 
Having said that, you should probably double check the actual reason of the failed deployment because that manifest is still there in the master branch as we speak: https://github.com/scylladb/scylla-operator/blob/master/examples/generic/cluster.yaml.
Hope that helps!
