### ISSUE TITLE
Upgrade path to enterprise version from scylla-operator-0.0-47cba43

### ISSUE THREAD

**Issue by eric-aops** [scylladb/scylla-operator#178]
Hi, 
Creating this issue to get in touch with the developers, as per advice from Moreno Garcia. 

We're currently running Scylla Operator using image `yanniszark/scylla-operator:v0.0-47cba43`. 
This version is deployed in all three environments, DEV (GKE), STG and PRD (on prem physical K8S clusters).
Our target is to upgrade to Enterprise 2020.1 as per Tomer Sandler: You need to upgrade to 4.0 (3.1 -> 3.2 -> 3.3 -> 4.0) and from 4.0 to Enterprise 2020.1. which was just officially announced yesterday.

Now, from the documentation at https://github.com/scylladb/scylla-operator/releases I see that the oldest release mentioning the yanniszark image is v0.1.4. Is it safe to upgrade the Scylla operator to that version, and would this allow to upgrade Scylla to v3.2.1?

Then would we have to go through all the releases of the Scylla Operator until we are on the version that can upgrade to Enterprise 2020.1?

Your advice is highly appreciated, we would like the process to upgrade as soon as possible. You can get in touch with us through this issue of course or through the Slack channel #harbour_one-scylla in the ScyllaDB Support workspace.

Kind regards, 

Eric V.

**Comment by zimnx** [comment]
Hello Eric,

None of operator version support Scylla minor or even major version upgrade. We don't even support Scylla Operator upgrades because it's still in beta version. 
Usually algorithm for Operator upgrade is to delete everything which was created using old version (cluster included), and recreate it using new one. Since you have a production env, I suppose it's not an option.

Other option would be to play around with PersistentVolumeClaims making sure that the same volumes are attached/detached from the same Scylla nodes and manually upgrading versions. Although this isn't tested at all.

What I would recommend is to use latest Operator available, create second Scylla cluster of the same size, use enterprise image and then migrate old cluster to new one using one of migrators available. Tomer or Moreno knows the details.
