### ISSUE TITLE
Document exposeOptions can't be changed on an existing cluster

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-operator#1966]
### What happened?

User needs to change how the cluster is exposed (leveraging `exposeOptions`)

### What did you expect to happen?

User should find on the documentation changing `exposeOptions` is not currently supported

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a cluster as private then switch `exposeOptions` to VPC-exposed

### Scylla Operator version

latest

### Kubernetes platform name and version

N/A

### Please attach the must-gather archive.

N/A

### Anything else we need to know?

Please document changing `exposeOptions` is not currently supported. Add link to GH issue that fixes this condition (if applicable) so users can track progress by themselves.

**Comment by tnozicka** [comment]
+1 for docs mention, probably an API comment, so it's visible in all the places

>Add link to GH issue that fixes this condition

I don't think that's something we want to get to at this point. It's a lot of edge cases. Orphan delete and recreate are probably good enough with all the pros and cons.

**Comment by tnozicka** [comment]
> what's the current workaround to change the exposeOptions?

I am not aware anyone going that path yet and since it's not supported there isn't a tested manual path either.

I assume you'd do the orphan delete so the child resources stay where they are and hope nothing else is immutable in the resources underneath. Possibly delete a problematic resource along the way and then recreate the ScyllaCluster letting it adopt the resources underneath or recreate the ones that are missing.

> Will orphan delete ScyllaCluster resource have any cons?

In general, your resources are unmanaged and not updatable for a while and there may be old resources left behind, if they wouldn't be created by the new definitions. And you loose a bit of  (probably insignificant) history / API atomicity. After the ScyllaCluster is recreated someone should go and clean the leftover resources without a controllerRef, if any.

That said, the supported path to get this changed is to create another ScyllaCluster to form a MultiDC, let the data sync and then destroy the original ScyllaCluster (datacenter). (Assuming the nature of the specific exposeOptions combination still allows the DCs to talk to each other.)
