### ISSUE TITLE
Move to modules for dependencies

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#23]
This is mostly a developer sanity request to be able to move out of GOPATH and what not now when the whole Go system (even kubernetes itself!) is starting to use it.

**Comment by yanniszark** [comment]
That would be awesome! :)
I would suggest using kubebuilder to generate a working example configuration and use it as a guide for changing the scylla-operator Makefile, go.mod files.
Also relevant for https://github.com/scylladb/scylla-operator/issues/22, since K8s dependencies need to be pinned all together.

**Comment by dahankzter** [comment]
Ah yes I tried a simple `go mod init` but the whole world blew up. :) There is some work with pinning properly and also I think some interfaces have changed if we want to bump kubernetes version at the same time.

**Comment by mmatczuk** [comment]
Relates to https://github.com/scylladb/scylla-operator/issues/56
