### ISSUE TITLE
Proposal: Create stable url

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-operator#336]
Related issue: https://github.com/scylladb/sphinx-scylladb-theme/issues/87

Every repository with docs could maintain a `stable` tag. The purpose is to have a default link to share that does not change, which is also beneficial for SEO purposes. 

An alternative solution is to build docs for ``master``. The downside of building docs for the branch where all changes are integrated is that this is frequently unstable or does not point yet to a version your readers can use.

## Create / Update the tag

To create a `stable` tag, the repo maintainer should run the following commands:

```
# Creates or updates the tag reference. You can change HEAD for a commit id.
git tag -f stable HEAD
# Publishes all local tags to the remote repository.
git push --tags
```
Every time you create a new release that's stable, the tag reference should be updated. Once the tag is created, please ping me, and I'll submit a PR including this tag to the docs build.

**Comment by zimnx** [comment]
This is painful to work with so I'm against it, because it requires a manual tag bump on every change which is being ported to release branch. Currently scylla-operator use branches instead of tags as a source of content to allow documentation changes even after release. 

What we could have, to improve SEO are static links pointing to latest_version branches.
For example:
http://operator.docs.scylladb.com/stable/manager.html
would redirect to:
http://operator.docs.scylladb.com/v1.0/manager.html
because `v1.0` branch is currenly considered stable.

**Comment by dgarcia360** [comment]
Thanks for the feedback @zimnx! In the end, I opted to edit the multiversion extension to rename the latest branch name as you proposed: https://github.com/scylladb/sphinx-scylladb-theme/pull/121
 
 With the next release of the theme, we'll have a new configuration option ``smv_rename_latest_version`` that will allow us to rename the latest version to ``stable`` in runtime.
 
 Please do not create the stable tag as suggested. Instead, I'll submit a new PR configuring this new option.
