### ISSUE TITLE
Resource requests and limit should be maintained as string

### ISSUE THREAD

**Issue by eljoth** [scylladb/scylla-operator#505]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently integers and strings are inconsistently used for resource specifications (see cluster definition, cpu=int, manager definition cpu=string). Best practice is to use strings for them.

**What is use case behind this feature:**
People using Pulumi cannot assign less than 1 cpu (for testing purposes, whatever) to the cluster since pulumi interprets the cpu value as an integer because in the values.yaml no string is set.

**Comment by tnozicka** [comment]
Can you be a bit more specific about what you want changed? e.g. link the definitions

In the API all should be IntOrString. Is this helm related only?

**Comment by eljoth** [comment]
Yes, it is a helm chart specific problem. Resource quotas should be set consistently in millicore:

https://github.com/scylladb/scylla-operator/blob/6ff5d1a5530d657512d8f70daa425cf0025cb77d/helm/scylla/values.yaml#L62

https://github.com/scylladb/scylla-operator/blob/6ff5d1a5530d657512d8f70daa425cf0025cb77d/helm/scylla/values.yaml#L65

should be set to `1000m` instead of `1` like already done e.g. in:

https://github.com/scylladb/scylla-operator/blob/6ff5d1a5530d657512d8f70daa425cf0025cb77d/helm/scylla-operator/values.yaml#L18

https://github.com/scylladb/scylla-operator/blob/6ff5d1a5530d657512d8f70daa425cf0025cb77d/helm/scylla-operator/values.yaml#L21

Changing this point will e.g. fix being not able to set the cpu limit without transformation in pulumi to any other value than integers (interpreted as full cpu, not millicores) because the cpu quota in the values file in the first case is interpreted as an integer due to the best practice of describing them with their unit.

**Comment by tnozicka** [comment]
To me, it sounds like Pulumi bug not using IntOrString/Quantity type properly.

The api definition itself says the field is either int or string, so both values are correct.
We use exactly the same type as kubernetes does, so you can see the rendered openAPIV3Schema for resources e.g. in
https://github.com/scylladb/scylla-operator/blob/7b1829f8fa4acc36fcd8dd6d2dee6e901945cec6/config/operator/crd/bases/scylla.scylladb.com_scyllaclusters.yaml#L556-L574

I don't think using `1000m` instead of `1` is the preferred way, kube docs use `1` consistently. It's just a unit of quantity, so in math you wouldn't prefer to write `1000/1000` instead of `1`.

Additionally
https://github.com/scylladb/scylla-operator/blob/6c9209d48b551558872b9d0587767672c658d5f0/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go#L37-L49
shows the empty unit as valid.

I guess it could be made an explicit string by putting quotes around it but as we are using the same type as kube does for resources, wouldn't you hit such issues with other objects, like pods, statefulsets, deployments, ...?

**Comment by eljoth** [comment]
This was not intended to be issued as a bug by no means.
To keep the analogy, in physics I would write 10mp/h instead of 10.

According to the [Google blog](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits)

> CPU
>
>CPU resources are defined in millicores. If your container needs two full cores to run, you would put the value “2000m”. If your container only needs ¼ of a core, you would put a value of “250m”.
>
>One thing to keep in mind about CPU requests is that if you put in a value larger than the core count of your biggest node, your pod will never be scheduled. Let’s say you have a pod that needs four cores, but your Kubernetes cluster is comprised of dual core VMs—your pod will never be scheduled!

In the [k8s docs for CPU resource](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/), they are also explicitly using a string in the yaml file instead of the integer value `1`.

As you also can see in the attached ticket for pulumi, I mentioned it as a bug there and here as a feature request. I think it should be kept consistent for all charts in the repo and set as a string as you also would write 500m for half a core and 500 would mean 500 cores.

**Comment by tnozicka** [comment]
> To keep the analogy, in physics I would write 10mph instead of 10

Just to close the analogy, at least in my view, that `m` is an `Si` prefix saying milli and the unit is implied (core shares) as well as for `1` (core shares). Similar to `k` saying it's `kilo`(*1000) and the implied unit depending on the resource is `B`.

Well, other parts of the docs use int, e.g. https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#consuming-extended-resources probably just opinionated or random as both are correct.

But back to your issue, I'd accept a PR changing `1` into `"1"` if you want to send one. I was objecting was using `"1000m"` instead of `"1"`.
