### ISSUE TITLE
RFE: Support multiple datacenter deployment

### ISSUE THREAD

**Issue by ngton** [scylladb/scylla-operator#555]
Hi, 

We're looking to deploy a distributed Scylla across multiple Kube (Openshift) clusters. Does this Operator provide functionality to deploy and manage that configuration or would we need to deploy the operator independently in both clusters and configure manually eg: https://docs.scylladb.com/operating-scylla/procedures/cluster-management/create_cluster_multidc/ 

Thanks

**Comment by tnozicka** [comment]
We don't yet support multiple datacenters. I guess you could try deploying the ScyllaCluster (1 dc) separately and manually connecting those but I haven't tried that.

**Comment by ashangit** [comment]
Hi,

We are working on supporting this feature on the scylla operator for hostNetwork cluster as a first step.
We would like to discuss with you the current implementation/design we have working on.
Here is the design doc: https://github.com/criteo-forks/scylla-operator/blob/b1566e281134668ecb03a896d69fd32fb33432c1/docs/design/MultiDc.md
And the PR pushed on our forks of the scylla operator: https://github.com/criteo-forks/scylla-operator/pull/10

Could you please let me know what are the next step to start discussing on this design/implementation?

**Comment by tnozicka** [comment]
Hi @ashangit,

thanks for presenting your design here. Unfortunately, we do not have the bandwidth to design the multi datacenter at this point as there are more pressing issues on our roadmap first.

I've took only a brief look at the design doc and the CRD, but I am not sure how you handle the muti-cluster (kubernetes) objects.

In my view, Scylla multi-dc needs multiple Kubernetes clusters (1 for each DC) otherwise you can just use racks for AZs. To handle multiple Kubernetes clusters I think we'd create a distinct CRD and a controller to handle managing multi-dc and creating a managed ScyllaCluster CR (a DC) handled by its own controller in each datacenter/kubernetes cluster. So when the DC running the multi-dc controller goes down, the local ScyllaCluster controller still reconciles the local datacenter so it doesn't go degraded in the meantime.

**Comment by geobeau** [comment]
In a nutshell, the current design add the possibility for any cluster to bootstrap using the seeds of another cluster (in a different kubernetes cluster). For that we need to be able to configure clusters in two modes:

- initCluster: being the one authorized to bootstrap with local seeds (like any other clusters)
- RemoteSeedCluster: Relying on an external seed (like a DNS record) to bootstrap from a distant cluster (the initCluster)

Once the bootstrap phase is finished (all node running at the same time once), they are managed by the operator like before.

Most of the code is made for:
- ensuring that once a cluster has finished bootstrapping it doesn't rely on the initCluster anymore for seeds
- fully support hostNetwork so that all nodes can communicate together

The way the external seed is generated is at the discretion of the human operator (it can be a DNS record, a VIP, etc...).

**Comment by tnozicka** [comment]
multidc is already available https://operator.docs.scylladb.com/v1.13/multidc/index.html
