### ISSUE TITLE
multi-tenant computing environment support

### ISSUE THREAD

**Issue by songdongsheng** [scylladb/scylla-operator#988]
Currently, scylla operator use cluster level permissions, e.g:

```
$ kubectl get clusterrole | grep scylla | awk '{print $1}'
scyllacluster-edit
scyllacluster-member
scyllacluster-view
scylladb:aggregate-to-scyllacluster-member
scylladb:controller:aggregate-to-operator
scylladb:controller:operator
```

This isn't feasible in some customer's environment, could scylla operator support use namespace level permissions only ?

**Comment by tnozicka** [comment]
The scylla operator is not meant to run in particular namespace. It extends the Kubernetes API with a CRD, that is cluster level, so it sets up cluster roles that are cluster level as well because the operator watches CRs across namespaces. The operator is a platform extension, it isn't an app that could be namespaced.
